stages:
  - .pre
  - build
  - test

Build Website:
  stage: build
  image: node:16-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build

Linter Test:
  stage: .pre
  image: node:16-alpine
  script:
    - npm ci
    - npm run lint

Unit Test:
  stage: .pre
  image: node:16-alpine
  script:
    - npm ci
    - npm test

Test Website:
  stage: test
  image: alpine
  script:
    - test -f build/index.html 