stages:
  - build
  - test
  - deploy

.Build Website:
  stage: build
  image: node:16-alpine
  script:
    - npm ci
    - npm run lint
    - npm test
    - npm run build
  artifacts:
    paths:
      - build

.Test Website:
  stage: test
  image: alpine
  script:
    - test -f build/index.html 

Deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - echo "Hello World" > test.txt
    - aws s3 cp test.txt s3://terraform-20220318033334413900000001/test.txt