stages:
  - build
  - packaging

variables:
  APP_VERSION: $CI_PIPELINE_IID

Build Website:
  stage: build
  image: node:16-alpine
  script:
    - npm ci
    - npm run lint
    - npm test
    - npm run build
    - echo $APP_VERSION > build/version.html
  artifacts:
    paths:
      - build

Building Docker Image:
  stage: packaging
  image: docker:20.10.13
  services: 
    - docker:20.10.13-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .       
    - docker image ls

